apiVersion: utils.mojaloop.io/v1alpha1
kind: ObjectSyncer
metadata:
  name: sc-velero-creds
  namespace: ${ARGOCD_ENV_sc_velero_config_namespace}
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  parameters:
    objectType: Secret
    source:
      namespace: ${ARGOCD_ENV_sc_velero_config_namespace}
      name: ${ARGOCD_ENV_object_storage_secret_name}
    destination:
      namespace: ${ARGOCD_ENV_velero_namespace}
      name: ${ARGOCD_ENV_object_storage_secret_name}
  providerConfigsRef:
    sourceK8sProviderName: "kubernetes-provider"
    destinationK8sProviderName: "sc-kubernetes-provider"
  managementPolicies:
    - "*"