{
 "title": "Netbird / Management",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(management_grpc_connected_streams_ratio,cluster)"
    }
   },
   {
    "name": "environment",
    "query": {
     "query": "label_values(management_grpc_connected_streams_ratio{cluster=\"$cluster\"},environment)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(management_grpc_connected_streams_ratio{cluster=\"$cluster\", environment=\"$environment\"},job)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(management_grpc_connected_streams_ratio{cluster=\"$cluster\", environment=\"$environment\", job=\"$job\"},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connected peers",
   "type": "stat",
   "description": "Number of active peer streams connected to the gRPC server",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "management_grpc_connected_streams_ratio",
     "legendFormat": "Connected grpc streams"
    }
   ]
  },
  { "title": "Core metrics / Network map", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "GetPeerNetworkMap Latency",
   "type": "timeseries",
   "description": "Duration of calculating the peer network map that is sent to the clients.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(increase(management_account_get_peer_network_map_duration_ms_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])) by (le,cluster,environment,job))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9,sum(increase(management_account_get_peer_network_map_duration_ms_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])) by (le,cluster,environment,job))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99,sum(increase(management_account_get_peer_network_map_duration_ms_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])) by (le,cluster,environment,job))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "UpdateAccountPeers Latency",
   "type": "timeseries",
   "description": "Duration of triggering the account peers update and preparing the required data for the network map being sent to the clients.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(increase(management_account_update_account_peers_duration_ms_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])) by (le,cluster,environment,job))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9,sum(increase(management_account_update_account_peers_duration_ms_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])) by (le,cluster,environment,job))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99,sum(increase(management_account_update_account_peers_duration_ms_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])) by (le,cluster,environment,job))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Core metrics / updatechannel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true
  },
  {
   "title": "Core metrics / store persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database persistence  latency",
     "type": "timeseries",
     "description": "Duration of how long it takes to save or delete an account in the store\n\nWill let you know if the DB is not keeping up with the requests coming from management",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(management_store_persistence_duration_ms_bucket[5m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(management_store_persistence_duration_ms_bucket[5m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(management_store_persistence_duration_ms_bucket[5m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Database transaction latency",
     "type": "timeseries",
     "description": "Duration of how long it takes to execute a transaction in the store\n\nWill let you know if the DB is not keeping up with the requests coming from management",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(management_store_transaction_duration_ms_bucket[5m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(management_store_transaction_duration_ms_bucket[5m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(management_store_transaction_duration_ms_bucket[5m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  },
  {
   "title": "Core metrics / IdP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "IdP authenticate request rate ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(management_idp_authenticate_request_counter_ratio_total{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])",
       "legendFormat": "{{cluster}}/{{environment}}/{{job}}"
      }
     ]
    },
    {
     "title": "IdP get_account request rate ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(management_idp_get_account_counter_ratio_total{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])",
       "legendFormat": "{{cluster}}/{{environment}}/{{job}}"
      }
     ]
    },
    {
     "title": "IdP update_user_meta request rate ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "rate(management_idp_update_user_meta_counter_ratio_total{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])",
       "legendFormat": "{{cluster}}/{{environment}}/{{job}}"
      }
     ]
    }
   ]
  },
  { "title": "HTTP metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Read request rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(management_http_request_counter_ratio_total{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\",method=~\"GET|OPTIONS\"}[$__rate_interval])) by (job,method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Write request rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(management_http_request_counter_ratio_total{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\",method=~\"POST|PUT|DELETE\"}[$__rate_interval])) by (job,method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Read request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(management_http_request_duration_ms_total_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\",type=~\"read\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(management_http_request_duration_ms_total_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\",type=~\"read\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(management_http_request_duration_ms_total_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\",type=~\"read\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Write request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(management_http_request_duration_ms_total_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\",type=~\"write\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(management_http_request_duration_ms_total_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\",type=~\"write\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(management_http_request_duration_ms_total_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\",type=~\"write\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Request rate by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(management_http_request_counter_ratio_total{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])) by (job,exported_endpoint,method)",
     "legendFormat": "{{method}}-{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "p90 latency by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(management_http_request_duration_ms_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[5m])) by (exported_endpoint,method,le))",
     "legendFormat": "{{method}}-{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "RPC metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync request rate ",
     "type": "timeseries",
     "description": "Number of sync gRPC requests from the peers to establish a connection and receive network map updates (update channel)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(management_grpc_sync_request_counter_ratio_total{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])) by (job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Login request rate ",
     "type": "timeseries",
     "description": "Duration of the login gRPC requests from the peers to authenticate and receive initial configuration and relay credentials",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(management_grpc_login_request_counter_ratio_total{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])) by (job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sync request latency",
     "type": "timeseries",
     "description": "Duration of the sync gRPC requests from the peers to establish a connection and receive network map updates (update channel)\n\nIf those are to high client will probably retry before management is able to respond\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(management_grpc_sync_request_duration_ms_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(management_grpc_sync_request_duration_ms_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(management_grpc_sync_request_duration_ms_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Login request latency",
     "type": "timeseries",
     "description": "Duration of the login gRPC requests from the peers to authenticate and receive initial configuration and relay credentials\n\nIf those are to high client will probably retry before management is able to respond\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(management_grpc_login_request_duration_ms_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(management_grpc_login_request_duration_ms_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(management_grpc_login_request_duration_ms_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\",host=~\"$host\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "GRPC Sync Latency",
     "type": "heatmap",
     "description": "Duration of the sync gRPC requests from the peers to establish a connection and receive network map updates (update channel).\n\nWhen you see a lighter color on a higher timing bucket, your users may experience issues.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum by(le) (increase(management_grpc_sync_request_duration_ms_bucket{environment=\"$environment\", application=\"management\", host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "gRPC Requests",
     "type": "barchart",
     "description": "Number of gRPC requests from the peers by message type",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(management_grpc_login_request_counter_ratio_total[$__rate_interval])",
       "legendFormat": "login"
      },
      {
       "expr": "rate(management_grpc_sync_request_counter_ratio_total[$__rate_interval])",
       "legendFormat": "sync"
      },
      {
       "expr": "rate(management_grpc_key_request_counter_ratio_total[$__rate_interval])",
       "legendFormat": "get key"
      }
     ]
    },
    {
     "title": "gRPC Sync Request p95 Duration",
     "type": "timeseries",
     "description": "Duration of the sync gRPC requests from the peers to establish a connection and receive network map updates (update channel) p95",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (irate(management_grpc_sync_request_duration_ms_bucket{environment=\"$environment\", application=\"management\", host=~\"$host\"}[$interval])))",
       "legendFormat": "GRPC Sync duration"
      }
     ]
    },
    {
     "title": "GRPC Login Latency",
     "type": "heatmap",
     "description": "Duration of the login gRPC requests from the peers to authenticate and receive initial configuration and relay credentials.\n\nWhen you see a lighter color on a higher timing bucket, your users may experience issues.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "sum by(le) (increase(management_grpc_login_request_duration_ms_bucket{environment=\"$environment\", application=\"management\", host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "gRPC Sync Request rate",
     "type": "timeseries",
     "description": "Number of sync gRPC requests per second from the peers to establish a connection and receive network map updates (update channel)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(management_grpc_sync_request_counter_ratio_total{environment=\"$environment\", application=\"management\", host=~\"$host\"}[$interval])",
       "legendFormat": "GRPC Sync request rate"
      }
     ]
    },
    {
     "title": "gRPC Login Request p95 Duration",
     "type": "timeseries",
     "description": "Duration of the login gRPC requests from the peers to authenticate and receive initial configuration and relay credentials p95",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(management_grpc_login_request_duration_ms_bucket{environment=\"$environment\", application=\"management\", host=~\"$host\"}[$interval])))",
       "legendFormat": "GRPC Login duration"
      }
     ]
    },
    {
     "title": "Store Persistence p95 Duration",
     "type": "timeseries",
     "description": "Duration of how long it takes to save or delete an account in the store p95",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(management_store_persistence_duration_ms_bucket{environment=\"$environment\", application=\"management\", host=~\"$host\"}[$interval])))",
       "legendFormat": "Store duration"
      }
     ]
    },
    {
     "title": "gRPC Login Request rate",
     "type": "timeseries",
     "description": "Number of login gRPC requests per second from the peers to authenticate and receive initial configuration and relay credentials",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(management_grpc_login_request_counter_ratio_total{environment=\"$environment\", application=\"management\", host=~\"$host\"}[$interval])",
       "legendFormat": "GRPC Login request rate"
      }
     ]
    },
    {
     "title": "Store Persistence latency",
     "type": "heatmap",
     "description": "Duration of how long it takes to save or delete an account in the store.\n\nWhen you see a lighter color on a higher timing bucket, your users may experience issues.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum by(le) (increase(management_store_persistence_duration_ms_bucket{application=\"management\", environment=\"$environment\", host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Global lock acquisition p95 Duration",
     "type": "barchart",
     "description": "Duration of how long a process holds the acquired global lock in the store",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (irate(management_store_global_lock_acquisition_duration_ms_bucket{environment=\"$environment\", application=\"management\", host=~\"$host\"}[$interval])))",
       "legendFormat": "Global lock duration"
      }
     ]
    },
    {
     "title": "IdP Requests",
     "type": "barchart",
     "description": "Number of requests to send to the IdP by request type.\n\nA high number for a long period might indicate an inconsistency between the number of local users and IdP.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(management_idp_authenticate_request_counter_ratio_total{application=\"management\", environment=\"$environment\", host=~\"$host\"}[$interval])",
       "legendFormat": "authenticate (mgtm->IdP)"
      },
      {
       "expr": "delta(management_idp_update_user_meta_counter_ratio_total{host=\"$host\", environment=\"$environment\"}[$interval])",
       "legendFormat": "update user meta"
      },
      {
       "expr": "delta(management_idp_get_account_counter_ratio_total{host=\"$host\", environment=\"$environment\"}[$interval])",
       "legendFormat": "get account"
      }
     ]
    },
    {
     "title": "Store Transaction latency",
     "type": "heatmap",
     "description": "Duration of how long it takes to execute a transaction in the store.\n\nWhen you see a lighter color on a higher timing bucket, your users may experience issues.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "sum by(le) (increase(management_store_transaction_duration_ms_bucket{application=\"management\", environment=\"$environment\", host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write HTTP API Requests p95 Duration (PUT/POST/DELETE)",
     "type": "timeseries",
     "description": "Duration of incoming write HTTP requests p95",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(le) (rate(management_http_request_duration_ms_total_bucket{application=\"management\", type=\"write\", environment=\"$environment\", host=~\"$host\"}[$interval]))",
       "legendFormat": "HTTP write duration"
      }
     ]
    },
    {
     "title": "HTTP API Requests p95 Duration",
     "type": "timeseries",
     "description": "Duration of incoming HTTP requests p95",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(management_http_request_duration_ms_total_bucket{application=\"management\", environment=\"$environment\", host=~\"$host\"}[$interval])))",
       "legendFormat": "HTTP request duration"
      }
     ]
    },
    {
     "title": "HTTP Read request counter",
     "type": "barchart",
     "description": "Number of incoming red HTTP requests by endpoint",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(management_http_response_counter_ratio_total{application=\"management\", environment=\"$environment\", method=\"GET\", code=~\"^2.+\", host=~\"$host\"}[$interval]) > 10",
       "legendFormat": "{{endpoint}} > 10"
      },
      {
       "expr": "sum by(environment) (delta(management_http_response_counter_ratio_total{host=\"$host\", environment=\"$environment\", method=\"GET\", code=~\"^2.+\"}[$interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Read HTTP API Requests p95 Duration (GET/OPTIONS)",
     "type": "timeseries",
     "description": "Duration of incoming read HTTP requests",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(management_http_request_duration_ms_total_bucket{application=\"management\", type=\"read\", environment=\"$environment\", host=~\"$host\"}[$interval])))",
       "legendFormat": "HTTP read duration"
      }
     ]
    },
    {
     "title": "Peer meta updates counter",
     "type": "barchart",
     "description": "Number of updates with new meta data from the peer.\n\nConstant high numbers of meta updates indicate a version with an issue. This can generate an issue on larger deployments since it will trigger an account-wide network map update.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(management_account_peer_meta_update_counter_ratio_total{application=\"management\", environment=\"$environment\", host=~\"$host\"}[$interval])",
       "legendFormat": "{{endpoint}} > 10"
      }
     ]
    },
    {
     "title": "HTTP Write request counter",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(management_http_response_counter_ratio_total{application=\"management\", environment=\"$environment\", method!~\"(GET|OPTIONS)\", code=~\"^2.+\", host=~\"$host\"}[$interval]) > 1",
       "legendFormat": "{{endpoint}} > 1"
      },
      {
       "expr": "sum by(environment) (delta(management_http_response_counter_ratio_total{host=\"$host\", environment=\"$environment\", method!~\"(GET|OPTIONS)\", code=~\"^2.+\"}[$interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Update Channel operations",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(management_updatechannel_close_one_duration_micro_count{application=\"management\", environment=\"$environment\", host=~\"$host\"}[$interval])",
       "legendFormat": "CloseOne"
      },
      {
       "expr": "sum(delta(management_updatechannel_send_duration_micro_count{host=\"$host\", environment=\"$environment\"}[$interval]))",
       "legendFormat": "Send"
      },
      {
       "expr": "sum(delta(management_updatechannel_create_duration_micro_count{host=\"$host\", environment=\"$environment\"}[$interval]))",
       "legendFormat": "Create"
      },
      {
       "expr": "delta(management_updatechannel_get_all_duration_micro_count{host=\"$host\", environment=\"$environment\"}[$interval])",
       "legendFormat": "GetAll"
      },
      {
       "expr": "delta(management_updatechannel_haschannel_duration_micro_count{host=\"$host\", environment=\"$environment\"}[$interval])",
       "legendFormat": "HasChannel"
      },
      {
       "expr": "delta(management_updatechannel_close_multiple_channels_count{host=\"$host\", environment=\"$environment\"}[$interval])",
       "legendFormat": "CloseMultiple"
      }
     ]
    },
    {
     "title": "Update Channel methods p95 Duration",
     "type": "timeseries",
     "description": "Duration of update channel operations by operation",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(management_updatechannel_close_one_duration_micro_bucket{application=\"management\", environment=\"$environment\", host=~\"$host\"}[$interval])))",
       "legendFormat": "CloseOne"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(management_updatechannel_send_duration_micro_bucket{host=\"$host\", environment=\"$environment\"}[$interval])))",
       "legendFormat": "Send"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(management_updatechannel_create_duration_micro_bucket{host=\"$host\", environment=\"$environment\"}[$interval])))",
       "legendFormat": "Create"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(management_updatechannel_get_all_duration_micro_bucket{host=\"$host\", environment=\"$environment\"}[$interval])))",
       "legendFormat": "GetAll"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(management_updatechannel_haschannel_duration_micro_bucket{host=\"$host\", environment=\"$environment\"}[$interval])))",
       "legendFormat": "CloseMultiple"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(management_updatechannel_close_multiple_channels_bucket{host=\"$host\", environment=\"$environment\"}[$interval])))",
       "legendFormat": "HasChannel"
      }
     ]
    },
    {
     "title": "Percentage of Recreated channels",
     "type": "timeseries",
     "description": "Ratio between closed and created update channels",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expression": "100-$A/$B*100", "type": "math" }
     ]
    },
    {
     "title": "UpdateChannel Queue length max",
     "type": "stat",
     "description": "Number of update messages piling up in the update channel queue",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (rate(management_grpc_updatechannel_queue_bucket{application=\"management\", environment=\"$environment\", host=~\"$host\"}[$interval]))",
       "legendFormat": "Connected grpc streams"
      }
     ]
    },
    {
     "title": "Connected peers historical",
     "type": "timeseries",
     "description": "Number of active peer streams connected to the gRPC server over time",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "management_grpc_connected_streams_ratio{application=\"management\", environment=\"$environment\", host=~\"$host\"}",
       "legendFormat": "Connected peers"
      }
     ]
    },
    {
     "title": "Update Channel heat map",
     "type": "heatmap",
     "description": "Number of update messages piling up in the update channel queue.\n\nA high queue number indicates either a network issue or a high number of account updates.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "targets": [
      {
       "expr": "sum by(le) (increase(management_grpc_updatechannel_queue_bucket{application=\"management\", environment=\"$environment\", host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "UpdateAccountPeers Latency",
     "type": "heatmap",
     "description": "Duration of triggering the account peers update and preparing the required data for the network map being sent to the clients.\n\nWhen you see a lighter color on a higher timing bucket, your users may experience issues.",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 149 },
     "targets": [
      {
       "expr": "sum by(le) (increase(management_account_update_account_peers_duration_ms_bucket{application=\"management\", environment=\"$environment\", host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NetworkMap Objects",
     "type": "heatmap",
     "description": "Number of objects in the network map like peers, routes, firewall rules, etc. that are sent to the clients",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 157 },
     "targets": [
      {
       "expr": "sum by(le) (increase(management_account_network_map_object_count_bucket{application=\"management\", environment=\"$environment\", host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}