apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: mailhog-auth
  namespace: mailhog
spec:
  selector:
    matchLabels:
      app: mailhog
  action: CUSTOM
  provider:
    name: ory-authz
  rules:
    - to:
        - operation:
            hosts: ["mailhog.*", "mailhog.*:*"]