image:
  repository: mailhog/mailhog
  tag: v1.0.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port:
    http: 8025
    smtp: 1025
  annotations: {}

ingress:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

podSecurityContext: {}

securityContext: {}

env: []

auth:
  enabled: false