{
 "title": "Mojaloop - Prometheus Remote write",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(prometheus_build_info,cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(prometheus_build_info{cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Headline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instructions",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "# Goal\n1. indicate problems with prometheus remote write\n2. performance metrics (request rate, latencies) related to remote write \n\n# Links\n- https://grafana.com/blog/2021/04/12/how-to-troubleshoot-remote-write-issues-in-prometheus/\n\n# Goal 1\nGoal 1 requires us to ensure \n1. remote write is not falling behind i.e. samples are not lost\n2. remote write should not have too many retries to the server\n3. remote write should not be operating at max capacity \n4. if remote write lost data, how much was it and when did it happen!\n\n\n# Goal 2\nshows general performance metrics\n1. request rate to remote server\n2. latency percentiles to remote server   "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Goal 1.1: Remote write should not fall behind",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Remote write sending delay",
   "type": "timeseries",
   "description": "Shows the amount of time after which samples are pushed to remote server after reading from WAL. \n- Expected range should be 3-10 seconds\n- increasing delay time means remote write is falling behind and will lead to data loss",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  prometheus_remote_storage_highest_timestamp_in_seconds{cluster=~\"$cluster\", instance=~\"$instance\"} \n-  \n  ignoring(remote_name, url) group_right(instance) (prometheus_remote_storage_queue_highest_sent_timestamp_seconds{cluster=~\"$cluster\", instance=~\"$instance\"} != 0)\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WAL watcher delay",
   "type": "timeseries",
   "description": "Shows the amount of time after which samples are being read by TSDB WAL watcher. The delay may increase in case of prometheus restarts (WAL replay). Considerable increase (20sec +)  suggests an outage and possible data loss. \n\n- Expected delay should be less than 20 seconds\n- increasing delay time means remote write is falling behind and will lead to data loss",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "-(prometheus_wal_watcher_current_segment{cluster=~\"$cluster\", instance=~\"$instance\"}\n - ignoring(consumer) group_left\nprometheus_tsdb_wal_segment_current{cluster=~\"$cluster\", instance=~\"$instance\"})\n",
     "legendFormat": "{{consumer}}"
    }
   ]
  },
  {
   "title": "Goal 1.2: Remote write data rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "No. of samples/metadata sent per second. \nShould show steady activity. Reduced activity should be coupled with increase in error rate or less timeseries data being scrapped. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "samples/sec" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_samples_total{cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{remote_name}}"
    }
   ]
  },
  {
   "title": "Retry rate",
   "type": "timeseries",
   "description": "No. of samples/metadata retried per second. \n\nIdeally zero. It indicates problems with the network or remote storage endpoint if there is a steady high rate for this metric. That may mean we need to reduce throughput of remote write to reduce load on the other end.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "samples/sec" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_samples_retried_total{cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{remote_name}}"
    }
   ]
  },
  {
   "title": "Goal 1.3: Remote write should not operate at max capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Remote write current shards",
   "type": "timeseries",
   "description": "No. of shards currently being used to send data to remote write endpoinds. This number should be less than max shards. A number near max shards mean that we may be throttled in case of any data increase",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards{cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{remote_name}}"
    }
   ]
  },
  {
   "title": "Remote write desired shards",
   "type": "timeseries",
   "description": "No. of shards estimated by algorithm to push data to remote endpoints ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards_desired{cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{remote_name}}"
    }
   ]
  },
  {
   "title": "Min - Max Shards",
   "type": "timeseries",
   "description": "Prometheus remote write min and max shards as per configuration",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards_min{cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{remote_name}} - min shards"
    },
    {
     "expr": "prometheus_remote_storage_shards_max{cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{remote_name}} - max shards"
    }
   ]
  },
  {
   "title": "Goal 1.4: Remote write data loss quantization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }
  },
  {
   "title": "Dropped samples rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "samples/sec" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_samples_dropped_total{cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{remote_name}}"
    }
   ]
  },
  {
   "title": "Failed samples rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "samples/sec" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_samples_failed_total{cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{remote_name}}"
    }
   ]
  },
  {
   "title": "Retried samples rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "samples/sec" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_samples_retried_total{cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{remote_name}}"
    }
   ]
  },
  {
   "title": "Enqueue attempt rate",
   "type": "timeseries",
   "description": "Rate of enqueue operation failure because a shard’s queue was full",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "attempt/sec" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_enqueue_retries_total{cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{remote_name}}"
    }
   ]
  },
  { "title": "Remote write latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Remote write request latency - p99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le,remote_name))",
     "legendFormat": "{{remote_name}}"
    }
   ]
  },
  {
   "title": "Remote write request latency - p90",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le,remote_name))",
     "legendFormat": "{{remote_name}}"
    }
   ]
  },
  {
   "title": "Remote write request latency - p50",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le,remote_name))",
     "legendFormat": "{{remote_name}}"
    }
   ]
  }
 ]
}