apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage-class.yaml

helmCharts:
  - name: openebs
    releaseName: openebs
    version: ${ARGOCD_ENV_sc_openebs_helm_version}
    repo: https://openebs.github.io/openebs
    valuesFile: openebs-values.yaml
    namespace: ${ARGOCD_ENV_sc_openebs_namespace}

patchesStrategicMerge:
  - kubectl-image-patch.yaml
