apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitlab-toolbox-restart
  namespace: ${ARGOCD_ENV_gitlab_namespace}
spec:
  schedule: '0 * * * *' # every hour
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: restart-toolbox
              image: bitnamilegacy/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  echo "Restarting gitlab-toolbox pod..."
                  kubectl -n gitlab rollout restart deployment gitlab-toolbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-toolbox-deployment-access
  namespace: gitlab
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["gitlab-toolbox"]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-toolbox-deployment-access
  namespace: gitlab
subjects:
  - kind: ServiceAccount
    name: default
    namespace: gitlab
roleRef:
  kind: Role
  name: gitlab-toolbox-deployment-access
  apiGroup: rbac.authorization.k8s.io