apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: ${ARGOCD_ENV_monitoring_app_namespace}
  annotations:
    argocd.argoproj.io/sync-wave: ${ARGOCD_ENV_monitoring_sync_wave}

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${ARGOCD_ENV_monitoring_monitoring_namespace}

  source:
    repoURL: ${ARGOCD_ENV_argocd_repo_url}
    targetRevision: ${ARGOCD_ENV_monitoring_application_gitrepo_tag}
    path: gitops/applications/overlays/cloud_provider/private-cloud/storage-provider/monitoring
    plugin:
      name: envsubst
      env:
        - name: "monitoring_kube_prometheus_helm_version"
          value: "${ARGOCD_ENV_monitoring_kube_prometheus_helm_version}"
        - name: "monitoring_namespace"
          value: "${ARGOCD_ENV_monitoring_monitoring_namespace}"

        - name: "prometheus_pvc_size"
          value: "${ARGOCD_ENV_monitoring_prometheus_pvc_size}"
        - name: "prometheus_scrape_interval"
          value: "${ARGOCD_ENV_monitoring_monitoring_prometheus_scrape_interval}"
        - name: "prometheus_retention_period"
          value: "${ARGOCD_ENV_monitoring_prometheus_retention_period}"
        # TODO: add prometheus before the config name
        - name: "tsdb_min_block_duration"
          value: "${ARGOCD_ENV_monitoring_prometheus_tsdb_min_block_duration}"
        - name: "tsdb_max_block_duration"
          value: "${ARGOCD_ENV_monitoring_prometheus_tsdb_max_block_duration}"
        - name: "resources_preset_bitnami"
          value: "${ARGOCD_ENV_monitoring_prometheus_resources_preset_bitnami}"
        - name: "remote_write_tenant_id"
          value: "${ARGOCD_ENV_monitoring_prometheus_remote_write_tenant_id}"
        - name: "cluster_label_value"
          value: storage
        - name: "prometheus_remote_write_endpoint"
          value: "https://mimir.${ARGOCD_ENV_monitoring_mimir_dns_subdomain}"

        - name: "alloy_target_loki_endpoint"
          value: "https://loki.${ARGOCD_ENV_monitoring_mimir_dns_subdomain}"
        - name: "monitoring_alloy_limits_memory"
          value: "${ARGOCD_ENV_monitoring_alloy_limits_memory}"
        - name: "monitoring_alloy_limits_cpu"
          value: "${ARGOCD_ENV_monitoring_alloy_limits_cpu}"
        - name: "alloy_log_rate_limit_per_pod"
          value: "200"
        - name: "alloy_log_burst_rate_limit_per_pod"
          value: "500"
        - name: "capi_cluster_name"
          value: "${ARGOCD_ENV_capi_cluster_name}"

