apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: alloy-config
  files:
  - ./alloy-config.alloy
  options:
    disableNameSuffixHash: true
- name: ksm-crd-config
  files:
    - ./ksm-crd-config.yaml
  options:
    disableNameSuffixHash: true
    
helmCharts:
  - name: kube-prometheus-stack
    releaseName: prom
    version: ${ARGOCD_ENV_monitoring_kube_prometheus_helm_version}
    repo: https://prometheus-community.github.io/helm-charts
    valuesFile: values-kube-prometheus.yaml
    namespace: ${ARGOCD_ENV_monitoring_namespace}
  - name: alloy
    releaseName: alloy
    version: 1.4.0
    repo: https://grafana.github.io/helm-charts
    valuesFile: values-alloy.yaml 
    namespace: ${ARGOCD_ENV_monitoring_namespace}
