alloy:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: ${ARGOCD_ENV_alloy_limits_cpu}
      memory: ${ARGOCD_ENV_alloy_limits_memory}
  extraConfig: |
    discovery.relabel "pod_logs" {
      targets = discovery.kubernetes.pods.targets
      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        action = "replace"
        target_label = "namespace"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        action = "replace"
        target_label = "pod"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        action = "replace"
        target_label = "container"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
        action = "replace"
        target_label = "app"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_component","__meta_kubernetes_pod_label_component"]
        action = "replace"
        target_label = "component"
        regex = "^;*([^;]+)(;.*)?$"
      }
      rule {
        source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
        action = "replace"
        target_label = "job"
        separator = "/"
        replacement = "$1"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_node_name"]
        action = "replace"
        target_label = "node_name"
      }
    }


    loki.source.kubernetes "pod_logs" {
      targets    = discovery.relabel.pod_logs.output
      forward_to = [loki.process.pod_logs.receiver]
    }

    loki.process "pod_logs" {
      stage.cri {}
      stage.limit {
        rate  = ${ARGOCD_ENV_alloy_log_rate_limit_per_pod}
        burst = ${ARGOCD_ENV_alloy_log_burst_rate_limit_per_pod}
        drop  = true
        by_label_name = "pod"
      }

      stage.static_labels {
          values = {
            cluster = "storage",
          }
      }

      forward_to = [loki.write.central_loki.receiver]
    }

    loki.write "central_loki" {
      endpoint {
        url = "${ARGOCD_ENV_alloy_target_loki_endpoint}/loki/api/v1/push" 
      }
    }