apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - virtualservice.yaml

helmCharts:
  - name: harbor
    releaseName: ${ARGOCD_ENV_harbor_app_name}
    version: ${ARGOCD_ENV_harbor_helm_version}
    repo: https://helm.goharbor.io
    valuesFile: harbor-values.yaml
    namespace: ${ARGOCD_ENV_harbor_namespace}

patches:
  - target:
      kind: Deployment
      name: .*harbor-core
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: HARBOR_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: harbor-secret
              key: harbor-password
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/strategy
        value:
          type: Recreate