apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: stunner-gatewayclass
spec:
  controllerName: "stunner.l7mp.io/gateway-operator"
  parametersRef:
    group: "stunner.l7mp.io"
    kind: GatewayConfig
    name: stunner-gatewayconfig
    namespace: "${ARGOCD_ENV_stunner_impl_namespace}"
  description: "STUNner is a WebRTC ingress gateway for Kubernetes"

---
apiVersion: stunner.l7mp.io/v1
kind: GatewayConfig
metadata:
  name: stunner-gatewayconfig
  namespace: "${ARGOCD_ENV_stunner_impl_namespace}"
spec:
  realm: stunner.l7mp.io
  authRef:
    name: ${ARGOCD_ENV_stunner_auth_secret}
    namespace: "${ARGOCD_ENV_stunner_impl_namespace}"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: udp-gateway
  namespace: "${ARGOCD_ENV_stunner_impl_namespace}"
  annotations:
    stunner.l7mp.io/service-type: NodePort
    #stunner.l7mp.io/port-preservation: "true"
    stunner.l7mp.io/nodeport: |
      {
        "udp-listener": ${ARGOCD_ENV_stunner_nodeport_port}
      }
spec:
  gatewayClassName: stunner-gatewayclass
  listeners:
    - name: udp-listener
      port: 3478
      protocol: TURN-UDP
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tcp-gateway
  namespace: "${ARGOCD_ENV_stunner_impl_namespace}"
  annotations:
    stunner.l7mp.io/service-type: NodePort
    #stunner.l7mp.io/port-preservation: "true"
    stunner.l7mp.io/nodeport: |
      {
        "tcp-listener": ${ARGOCD_ENV_stunner_nodeport_port}
      }
spec:
  gatewayClassName: stunner-gatewayclass
  listeners:
    - name: tcp-listener
      port: 3478
      protocol: TURN-TCP
---
apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: stunner-headless
  namespace: "${ARGOCD_ENV_stunner_impl_namespace}"
spec:
  parentRefs:
    - name: udp-gateway
    - kind: Service
      name: stunner-internal-mirror 
  rules:
    - backendRefs:
        - group: stunner.l7mp.io
          kind: StaticService
          name: all-internal-pods
---
apiVersion: stunner.l7mp.io/v1
kind: StaticService
metadata:
  name: all-internal-pods
  namespace: "${ARGOCD_ENV_stunner_impl_namespace}"
spec:
  # Replace with your actual K8s Pod CIDR for better security
  # Or use 0.0.0.0/0 for absolute wildcard access
  prefixes:
    - 0.0.0.0/0
