_DEFINE:
  DEPLOYMENT: &DEPLOYMENT
    replicaCount: 1
    readinessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 1
    sidecar:
      readinessProbe:
        initialDelaySeconds: 5
      livenessProbe:
        initialDelaySeconds: 5
  DEPLOYMENT_PROBE: &DEPLOYMENT_PROBE
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 2
      httpGet:
        path: /live
  HANDLER_PROBE: &HANDLER_PROBE
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 2
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 6
      httpGet:
        path: /health
    readinessProbe:
      enabled: false
  CONFIG: &CONFIG
    replicaCount: 1
    config: &BASE_CONFIG
      event_log_filter: ""
      log_level: warn
  PROXY_CONFIG: &PROXY_CONFIG
    config:
      <<: *BASE_CONFIG
      proxy_cache:
        enabled: false
        proxyConfig:
          host: mojaloop-redis
          cluster:
            - host: mojaloop-redis-leader
              port: 6379
  SERVICE: &SERVICE
    <<: [*DEPLOYMENT, *DEPLOYMENT_PROBE, *CONFIG]
  SERVICE_WITH_PROXY: &SERVICE_WITH_PROXY
    <<: [*DEPLOYMENT, *DEPLOYMENT_PROBE, *PROXY_CONFIG]
  HANDLER: &HANDLER
    <<: [*DEPLOYMENT, *HANDLER_PROBE, *CONFIG]
  HANDLER_WITH_PROXY: &HANDLER_WITH_PROXY
    <<: [*DEPLOYMENT, *HANDLER_PROBE, *PROXY_CONFIG]
account-lookup-service:
  account-lookup-service: *SERVICE_WITH_PROXY
  account-lookup-service-admin: *SERVICE_WITH_PROXY
quoting-service:
  quoting-service: *SERVICE
  quoting-service-handler: *HANDLER_WITH_PROXY
ml-api-adapter:
  ml-api-adapter-service: *SERVICE
  ml-api-adapter-handler-notification: *HANDLER_WITH_PROXY
centralledger:
  centralledger-service: *SERVICE
  centralledger-handler-transfer-prepare: *HANDLER_WITH_PROXY
  centralledger-handler-transfer-position: *HANDLER
  centralledger-handler-transfer-position-batch: *HANDLER
  centralledger-handler-transfer-get: *HANDLER
  centralledger-handler-transfer-fulfil: *HANDLER
  centralledger-handler-timeout: *HANDLER
  centralledger-handler-admin-transfer: *HANDLER
centralsettlement:
  centralsettlement-service: *CONFIG
  centralsettlement-handler-deferredsettlement: *CONFIG
  centralsettlement-handler-grosssettlement:
    replicaCount: 0
    config: *BASE_CONFIG
  centralsettlement-handler-rules: *CONFIG
transaction-requests-service: *SERVICE
thirdparty:
  auth-svc:
    replicaCount: 1
  consent-oracle:
    replicaCount: 1
  tp-api-svc:
    replicaCount: 1
mojaloop-bulk:
  bulk-api-adapter:
    bulk-api-adapter-service: *CONFIG
    bulk-api-adapter-handler-notification: *CONFIG
  bulk-centralledger:
    cl-handler-bulk-transfer-prepare: *CONFIG
    cl-handler-bulk-transfer-fulfil: *CONFIG
    cl-handler-bulk-transfer-processing: *CONFIG
    cl-handler-bulk-transfer-get: *CONFIG
