mcm-db:
  external_resource_config:
    password_key_name: mcm_password
account-lookup-db:
  external_resource_config:
    password_key_name: account_lookup_password
central-ledger-db:
  external_resource_config:
    password_key_name: central_ledger_password
bulk-mongodb:
  external_resource_config:
    password_key_name: bulk_mongodb_password
reporting-events-mongodb:
  external_resource_config:
    password_key_name: reporting_events_mongodb_password
ttk-mongodb:
  external_resource_config:
    password_key_name: ttk_mongodb_password
mojaloop-kafka:
  external_resource_config:
    password_key_name: kafka_password
keycloak-db:
  external_resource_config:
    password_key_name: keycloak_password
keto-db:
  external_resource_config:
    password_key_name: keto_password
    monolith_db_server: common_platform_db
kratos-db:
  external_resource_config:
    password_key_name: kratos_password
