apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/rmb938/hostport-allocator/releases/download/v${ARGOCD_ENV_hostport_allocator_version}/hostport-allocator.yaml
  - namespace.yaml
