apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# TODO: we need to review if we need cloudwatch exporter in the first place or not
# configMapGenerator:
# - files:
#   - ./cloudwatch-exporter-config.yaml
#   name: cloudwatch-exporter-config

configMapGenerator:
- name: alloy-config
  files:
  - ./alloy-config.alloy
  options:
    disableNameSuffixHash: true
- name: loki-ruler-rules
  files:
  - rules.yaml=./loki-ruler-rules.yaml
  options:
    disableNameSuffixHash: true


# resources:
# - cloudwatch-exporter.yaml

helmCharts:
  - name: mimir-distributed
    releaseName: central-monitoring
    version: ${ARGOCD_ENV_grafana_mimir_helm_version}
    repo: https://grafana.github.io/helm-charts
    valuesFile: values-mimir.yaml
    namespace: ${ARGOCD_ENV_monitoring_namespace}
  - name: kube-prometheus-stack
    releaseName: prom
    version: ${ARGOCD_ENV_kube_prometheus_helm_version}
    repo: https://prometheus-community.github.io/helm-charts
    valuesFile: values-kube-prometheus.yaml
    namespace: ${ARGOCD_ENV_monitoring_namespace}
  - name: loki
    releaseName: ${ARGOCD_ENV_loki_release_name} 
    version: ${ARGOCD_ENV_loki_helm_version}         
    repo: https://grafana.github.io/helm-charts
    valuesFile: values-loki.yaml
    namespace: ${ARGOCD_ENV_monitoring_namespace}
  - name: tempo-distributed
    releaseName: central
    version: ${ARGOCD_ENV_tempo_helm_version}    # Expose via config variables
    repo:  https://grafana.github.io/helm-charts
    valuesFile: values-tempo.yaml
    namespace: ${ARGOCD_ENV_monitoring_namespace}
  - name: tempo-vulture
    releaseName: central
    version: 0.9.1
    repo:  https://grafana.github.io/helm-charts
    valuesFile: values-vulture.yaml
    namespace: ${ARGOCD_ENV_monitoring_namespace}
  - name: alloy
    releaseName: alloy
    version: 1.4.0           #parametrize helm version
    repo: https://grafana.github.io/helm-charts
    valuesFile: values-alloy.yaml
    namespace: ${ARGOCD_ENV_monitoring_namespace}