tempo:
  extraArgs:
    "config.expand-env": true
  extraEnvFrom:
    - secretRef:
        name: "tempo-${ARGOCD_ENV_dns_hyphenated_subdomain}"
  storage:
    trace:
      backend: s3
      s3:
        forcepathstyle: true
        endpoint: cephobjectstore.ccdev.drpp-onprem.global
        insecure: true
        bucket: "tempo-${ARGOCD_ENV_dns_hyphenated_subdomain}" 
        region: us-east-1
        access_key: $${username}
        secret_key: $${password}



