tempoAddress:
  # -- the url towards your Tempo distributor, e.g. http://distributor
  push: http://single-binary-tempo:4317
  # -- the url towards your Tempo query-frontend, e.g. http://query-frontend:3200
  query: http://single-binary-tempo:3200
podMonitor:
  enabled: true