{
 "title": "Ceph - Object storage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(radosgw_usage_user_total_bytes,cluster)"
    }
   },
   {
    "name": "bucket",
    "query": {
     "query": "label_values(radosgw_usage_bucket_bytes{cluster=~\"$cluster\"},bucket)"
    }
   },
   {
    "name": "user",
    "query": {
     "query": "label_values(radosgw_usage_user_total_bytes{cluster=~\"$cluster\"},user)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users approaching max quota limit",
   "type": "table",
   "description": "Indicates buckets which are very near to bucket quota limit. NOTE: bucket quota is being enforced using users quota",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(radosgw_usage_user_total_bytes{cluster=~\"$cluster\",user=~\"$user\"}) by (user) / \nsum(radosgw_usage_user_quota_size_bytes{cluster=~\"$cluster\",user=~\"$user\"} ) by (user) > 0.8 ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "User metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "User data Size",
   "type": "timeseries",
   "description": "Total size of data owned by the user across all buckets",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(radosgw_usage_user_total_bytes{cluster=~\"$cluster\",user=~\"$user\"}) by (user)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User data quota",
   "type": "timeseries",
   "description": "Maximum data storage capacity for the given user",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(radosgw_usage_user_quota_size_bytes{cluster=~\"$cluster\",user=~\"$user\"}) by (user)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User data quota utilization (%)",
   "type": "timeseries",
   "description": "Percentage of storage quota used by the user",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(radosgw_usage_user_total_bytes{cluster=~\"$cluster\",user=~\"$user\"}) by (user) / \nsum(radosgw_usage_user_quota_size_bytes{cluster=~\"$cluster\",user=~\"$user\"} ) by (user)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bucket metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Bucket Size",
   "type": "timeseries",
   "description": "Total size of the bucket",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(radosgw_usage_bucket_bytes{cluster=~\"$cluster\",bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucket size quota",
   "type": "timeseries",
   "description": "Max. size the bucket is allowed to grow. 0 indicates unlimited",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(radosgw_usage_bucket_quota_size_bytes{cluster=~\"$cluster\",bucket=~\"$bucket\"} ) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucket quota utilization",
   "type": "timeseries",
   "description": "Percentage of bucket storage quota utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "\n(sum(radosgw_usage_bucket_bytes{cluster=~\"$cluster\",bucket=~\"$bucket\"}) by (bucket) / \nsum(radosgw_usage_bucket_quota_size_bytes{cluster=~\"$cluster\",bucket=~\"$bucket\"} + 1) by (bucket) ) <=1 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucket object count",
   "type": "timeseries",
   "description": "No. of objects in the bucket",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(radosgw_usage_bucket_objects{cluster=~\"$cluster\",bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucket object quota",
   "type": "timeseries",
   "description": "Max No. of objects allowed in the bucket. -1 indicates \"no limit\"",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(radosgw_usage_bucket_quota_size_objects{cluster=~\"$cluster\",bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}