{
 "title": "DB cost estimate",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(haproxy_process_requests_total,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(haproxy_process_requests_total{cluster=\"$cluster\"},namespace)"
    }
   },
   { "name": "dbs", "label": "Databases", "query": "mojaloop,platform,mongodb" },
   {
    "name": "mysql_db",
    "label": "MySQL DB",
    "query": {
     "query": "label_values(haproxy_process_requests_total{cluster=\"$cluster\", namespace=\"$namespace\"},service)"
    }
   },
   { "name": "mongo_db", "label": "Mongo DB", "query": "common-mongodb" }
  ]
 },
 "panels": [
  {
   "title": "Storage cost",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "\nkubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",persistentvolumeclaim=~\".*$dbs.*(db-pxc|rs0).*\",job=\"kubelet\"}/1024/1024/1024 * 0.1\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request cost",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "increase(haproxy_process_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\",service=~\".*${dbs}.*\"}[$__range]) / 1000 / 1000 * 0.2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Egress traffic cost",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "increase(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\".*${dbs}.*(haproxy|mongos).*\",interface=\"eth0\"}[$__range]) / 1024/1024/1024 * 0.09",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mysql",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",persistentvolumeclaim=~\".*$mysql_db.*\",job=\"kubelet\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Request rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\",service=~\".*${mysql_db}.*\"}[$__rate_interval])",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Egress traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\".*${mysql_db}.*haproxy.*\",interface=\"eth0\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "mongodb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",persistentvolumeclaim=~\".*$mongo_db.*\",job=\"kubelet\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    { "title": "Request rate", "type": "timeseries", "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 }, "fieldConfig": { "defaults": { "unit": "reqps" } } },
    {
     "title": "Egress traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\".*${mongo_db}-mongos.*\",interface=\"eth0\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}