{
 "title": "Kubernetes / Capacity planning",
 "description": "Shows cpu and memory utilisation in relationship with CPU ",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests,cluster)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests{cluster=~\"$cluster\"},job)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests{cluster=\"$cluster\", job=\"$job\"},namespace)"
    }
   },
   { "name": "pod_filter", "label": "pod filter", "query": ".+" },
   { "name": "timeperiod", "query": "24h" }
  ]
 },
 "panels": [
  { "title": "Global view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", cluster=\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_cpu_cores{cluster=\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"} - node_memory_MemAvailable_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Excess CPU request",
   "type": "table",
   "description": "Shows pods which have used less than 50% of requested CPU over the last 24h",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"\", cluster=\"$cluster\"}[$timeperiod]) \n/ on (namespace,pod,container) group_left\nkube_pod_container_resource_requests{ resource=\"cpu\" , cluster=\"$cluster\"} < 0.5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Excess memory request",
   "type": "table",
   "description": "Shows pods which have used less than 50% of RAM over the last 24h",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max_over_time(container_memory_working_set_bytes{image!=\"\", container!=\"\", cluster=\"$cluster\"}[$timeperiod])\n/ on (namespace,pod,container) group_left\nkube_pod_container_resource_requests{ resource=\"memory\" , cluster=\"$cluster\"} < 0.5",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Namespace view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Resource breakdown by namespace",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", job=~\"$job\", cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", job=~\"$job\", cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", job=~\"$job\", cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", job=~\"$job\", cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", container!=\"\", cluster=\"$cluster\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Pod view",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource breakdown by pod (selected namespace)",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"cpu\", job=~\"$job\", cluster=\"$cluster\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",resource=\"cpu\", job=~\"$job\", cluster=\"$cluster\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"memory\", job=~\"$job\", cluster=\"$cluster\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", resource=\"memory\", job=~\"$job\", cluster=\"$cluster\"}) by (pod)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", image!=\"\", container!=\"\", cluster=\"$cluster\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Resource breakdown by pod (pod filter)",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", job=~\"$job\", pod=~\".*$pod_filter.*\", cluster=\"$cluster\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", job=~\"$job\", pod=~\".*$pod_filter.*\", cluster=\"$cluster\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", job=~\"$job\", pod=~\".*$pod_filter.*\", cluster=\"$cluster\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", job=~\"$job\", pod=~\".*$pod_filter.*\", cluster=\"$cluster\"}) by (pod)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".*$pod_filter.*\", image!=\"\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\", container!=\"\", pod=~\".*$pod_filter.*\", cluster=\"$cluster\"}) by (pod)"
      }
     ]
    }
   ]
  }
 ]
}