{
 "title": "Loki Metrics",
 "description": "Shows metrics of log errors from Loki",
 "tags": [
  "loki",
  "logs",
  "ruler"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "DNS Timeout Errors",
   "type": "timeseries",
   "description": "DNS timeout errors (EAI_AGAIN)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "logs/sec" } },
   "targets": [
    {
     "expr": "topk(5, loki_log_dns_timeout_lines_rate)",
     "legendFormat": "{{namespace}}/{{app}}/{{container}}"
    }
   ]
  },
  {
   "title": "DNS Not Found Errors",
   "type": "timeseries",
   "description": "DNS not found errors (ENOTFOUND)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "logs/sec" } },
   "targets": [
    {
     "expr": "topk(5, loki_log_dns_not_found_lines_rate)",
     "legendFormat": "{{namespace}}/{{app}}/{{container}}"
    }
   ]
  },
  {
   "title": "MySQL Connection Lost",
   "type": "timeseries",
   "description": "MySQL connection lost errors",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "logs/sec" } },
   "targets": [
    {
     "expr": "topk(5, loki_log_mysql_connection_lost_lines_rate)",
     "legendFormat": "{{namespace}}/{{app}}/{{container}}"
    }
   ]
  }
 ]
}