{
 "title": "Loki - Log statistics - Overview",
 "description": "Shows overview of log statistics in Loki",
 "tags": [
  "loki",
  "logs"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Estimated loki storage per stream per day ",
   "type": "timeseries",
   "description": "Shows the estimated amount of storage needed to store 1 day worth of data for given stream",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(3,loki_log_bytes_rate) * 3600*24",
     "legendFormat": "{{namespace}}/{{app}}/{{container}}"
    }
   ]
  },
  {
   "title": "Top pods by error logs",
   "type": "barchart",
   "description": "Shows top pods with highest error rate fractions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(\n  3,\n  sum_over_time(loki_log_error_lines_rate[1h])\n  /\n  sum_over_time(loki_log_lines_rate[1h])\n)\n",
     "legendFormat": "{{namespace}}/{{app}}/{{container}}"
    }
   ]
  },
  {
   "title": "DNS Timeout Errors",
   "type": "timeseries",
   "description": "DNS timeout errors (EAI_AGAIN)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "logs/sec" } },
   "targets": [
    {
     "expr": "topk(5, loki_log_dns_timeout_lines_rate)",
     "legendFormat": "{{namespace}}/{{app}}/{{container}}"
    }
   ]
  },
  {
   "title": "DNS Not Found Errors",
   "type": "timeseries",
   "description": "DNS not found errors (getaddrinfo ENOTFOUND)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "logs/sec" } },
   "targets": [
    {
     "expr": "topk(5, loki_log_dns_not_found_lines_rate)",
     "legendFormat": "{{namespace}}/{{app}}/{{container}}"
    }
   ]
  },
  {
   "title": "MySQL Connection Lost",
   "type": "timeseries",
   "description": "MySQL connection lost errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "logs/sec" } },
   "targets": [
    {
     "expr": "topk(5, loki_log_mysql_connection_lost_lines_rate)",
     "legendFormat": "{{namespace}}/{{app}}/{{container}}"
    }
   ]
  }
 ]
}