{
 "title": "Mojaloop Connector",
 "tags": [
  "mojaloop",
  "connector",
  "nodejs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(mojaloop_connector_default_process_start_time_seconds,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Transfer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Outbound Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mojaloop_connector_outbound_party_lookup_request_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Party Lookup Requests"
    },
    {
     "expr": "rate(mojaloop_connector_outbound_quote_request_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Quote Requests"
    },
    {
     "expr": "rate(mojaloop_connector_outbound_transfer_prepare_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Transfer Prepares"
    }
   ]
  },
  {
   "title": "Outbound Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mojaloop_connector_outbound_party_lookup_response_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Party Lookup Responses"
    },
    {
     "expr": "rate(mojaloop_connector_outbound_quote_response_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Quote Responses"
    },
    {
     "expr": "rate(mojaloop_connector_outbound_transfer_fulfil_response_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Transfer Fulfils"
    }
   ]
  },
  {
   "title": "Total Party Lookups",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mojaloop_connector_outbound_party_lookup_request_count{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Total Quotes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mojaloop_connector_outbound_quote_request_count{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Total Transfers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mojaloop_connector_outbound_transfer_prepare_count{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Transfer Success Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mojaloop_connector_outbound_transfer_fulfil_response_count{namespace=\"$namespace\"} / mojaloop_connector_outbound_transfer_prepare_count{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Party Lookup Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(mojaloop_connector_outbound_party_lookup_latency_bucket{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, rate(mojaloop_connector_outbound_party_lookup_latency_bucket{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(mojaloop_connector_outbound_party_lookup_latency_bucket{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Quote Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(mojaloop_connector_outbound_quote_request_latency_bucket{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, rate(mojaloop_connector_outbound_quote_request_latency_bucket{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(mojaloop_connector_outbound_quote_request_latency_bucket{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Transfer Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(mojaloop_connector_outbound_transfer_latency_bucket{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, rate(mojaloop_connector_outbound_transfer_latency_bucket{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(mojaloop_connector_outbound_transfer_latency_bucket{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "FX Transfer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "FX Outbound Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mojaloop_connector_outbound_fx_quote_request_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "FX Quote Requests"
    },
    {
     "expr": "rate(mojaloop_connector_outbound_fx_transfer_prepare_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "FX Transfer Prepares"
    }
   ]
  },
  {
   "title": "FX Outbound Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mojaloop_connector_outbound_fx_quote_response_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "FX Quote Responses"
    },
    {
     "expr": "rate(mojaloop_connector_outbound_fx_transfer_fulfil_response_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "FX Transfer Fulfils"
    }
   ]
  },
  {
   "title": "Total FX Quotes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mojaloop_connector_outbound_fx_quote_request_count{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Total FX Transfers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mojaloop_connector_outbound_fx_transfer_prepare_count{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "FX Transfer Success Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mojaloop_connector_outbound_fx_transfer_fulfil_response_count{namespace=\"$namespace\"} / mojaloop_connector_outbound_fx_transfer_prepare_count{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "FX Quote Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(mojaloop_connector_outbound_fx_quote_latency_bucket{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, rate(mojaloop_connector_outbound_fx_quote_latency_bucket{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(mojaloop_connector_outbound_fx_quote_latency_bucket{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "FX Transfer Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(mojaloop_connector_outbound_fx_transfer_latency_bucket{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, rate(mojaloop_connector_outbound_fx_transfer_latency_bucket{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(mojaloop_connector_outbound_fx_transfer_latency_bucket{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Process Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(mojaloop_connector_default_process_cpu_user_seconds_total{namespace=\"$namespace\"}[5m])",
     "legendFormat": "User CPU"
    },
    {
     "expr": "rate(mojaloop_connector_default_process_cpu_system_seconds_total{namespace=\"$namespace\"}[5m])",
     "legendFormat": "System CPU"
    },
    {
     "expr": "rate(mojaloop_connector_default_process_cpu_seconds_total{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mojaloop_connector_default_process_resident_memory_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "mojaloop_connector_default_process_virtual_memory_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "mojaloop_connector_default_process_heap_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Heap Size"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mojaloop_connector_default_process_open_fds{namespace=\"$namespace\"}",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "mojaloop_connector_default_process_max_fds{namespace=\"$namespace\"}",
     "legendFormat": "Max FDs"
    }
   ]
  },
  {
   "title": "Process Start Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mojaloop_connector_default_process_start_time_seconds{namespace=\"$namespace\"} * 1000"
    }
   ]
  },
  { "title": "Node.js Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mojaloop_connector_default_nodejs_eventloop_lag_seconds{namespace=\"$namespace\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "mojaloop_connector_default_nodejs_eventloop_lag_mean_seconds{namespace=\"$namespace\"}",
     "legendFormat": "Mean"
    },
    {
     "expr": "mojaloop_connector_default_nodejs_eventloop_lag_p50_seconds{namespace=\"$namespace\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "mojaloop_connector_default_nodejs_eventloop_lag_p90_seconds{namespace=\"$namespace\"}",
     "legendFormat": "p90"
    },
    {
     "expr": "mojaloop_connector_default_nodejs_eventloop_lag_p99_seconds{namespace=\"$namespace\"}",
     "legendFormat": "p99"
    },
    {
     "expr": "mojaloop_connector_default_nodejs_eventloop_lag_min_seconds{namespace=\"$namespace\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "mojaloop_connector_default_nodejs_eventloop_lag_max_seconds{namespace=\"$namespace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "mojaloop_connector_default_nodejs_eventloop_lag_stddev_seconds{namespace=\"$namespace\"}",
     "legendFormat": "StdDev"
    }
   ]
  },
  {
   "title": "Active Resources by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mojaloop_connector_default_nodejs_active_resources{namespace=\"$namespace\",type!=\"\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total Active Resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mojaloop_connector_default_nodejs_active_resources_total{namespace=\"$namespace\"}",
     "legendFormat": "Total Resources"
    }
   ]
  },
  {
   "title": "Total Active Handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mojaloop_connector_default_nodejs_active_handles_total{namespace=\"$namespace\"}",
     "legendFormat": "Total Handles"
    }
   ]
  },
  {
   "title": "Total Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mojaloop_connector_default_nodejs_active_requests_total{namespace=\"$namespace\"}",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Active Handles by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mojaloop_connector_default_nodejs_active_handles{namespace=\"$namespace\",type!=\"\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Node.js Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mojaloop_connector_default_nodejs_heap_size_total_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Total Heap"
    },
    {
     "expr": "mojaloop_connector_default_nodejs_heap_size_used_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "mojaloop_connector_default_nodejs_external_memory_bytes{namespace=\"$namespace\"}",
     "legendFormat": "External Memory"
    }
   ]
  },
  {
   "title": "Heap Space Size (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mojaloop_connector_default_nodejs_heap_space_size_total_bytes{namespace=\"$namespace\",space!=\"\"}",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "Heap Space Size (Used)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mojaloop_connector_default_nodejs_heap_space_size_used_bytes{namespace=\"$namespace\",space!=\"\"}",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "Heap Space Size (Available)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mojaloop_connector_default_nodejs_heap_space_size_available_bytes{namespace=\"$namespace\",space!=\"\"}",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mojaloop_connector_default_nodejs_gc_duration_seconds_count{namespace=\"$namespace\",kind=\"minor\"}[5m])",
     "legendFormat": "Minor GC"
    },
    {
     "expr": "rate(mojaloop_connector_default_nodejs_gc_duration_seconds_count{namespace=\"$namespace\",kind=\"major\"}[5m])",
     "legendFormat": "Major GC"
    },
    {
     "expr": "rate(mojaloop_connector_default_nodejs_gc_duration_seconds_count{namespace=\"$namespace\",kind=\"incremental\"}[5m])",
     "legendFormat": "Incremental GC"
    }
   ]
  }
 ]
}