{
 "title": "Network - Traffic Analyser",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_uname_info,cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info{cluster=\"$cluster\"},nodename)"
    }
   },
   {
    "name": "ignore_pods_regexp",
    "query": ".+rbdplugin.+|coredns-nodecache.+|.+node-exporter.+|.+cephfsplugin.+|calico-node.+|node-debugger.+"
   },
   { "name": "pod_filter", "label": "pod filter", "query": ".+" }
  ]
 },
 "panels": [
  { "title": "Node traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Eth0 TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"eth.+\"}[$__rate_interval])\n",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "vxlan.calico TX",
   "type": "timeseries",
   "description": "Displays data transmitted to peer nodes within the Kubernetes cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"vxlan.calico\"}[$__rate_interval])\n",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "wt0 TX",
   "type": "timeseries",
   "description": "Displays data transmitted over VPN",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"wt.+\"}[$__rate_interval])\n",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Eth0 RX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"eth.+\"}[$__rate_interval])\n",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "vxlan.calico RX",
   "type": "timeseries",
   "description": "Displays data transmitted to peer nodes within the Kubernetes cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"vxlan.calico\"}[$__rate_interval])\n",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "wt0 RX",
   "type": "timeseries",
   "description": "Displays data received over VPN",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"wt.+\"}[$__rate_interval])\n",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  { "title": "Pod traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pod TX",
   "type": "timeseries",
   "description": "Displays data transmitted by each pod",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",node=~\"$node\",pod!~\"$ignore_pods_regexp\",pod!=\"\",pod=~\".*$pod_filter.*\"}[$__rate_interval])) by (node,pod)\n",
     "legendFormat": "{{node}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Pod RX",
   "type": "timeseries",
   "description": "Displays data received by each pod",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=~\"$cluster\",node=~\"$node\",pod!~\"$ignore_pods_regexp\",pod!=\"\",pod=~\".*$pod_filter.*\"}[$__rate_interval])) by (node,pod)\n",
     "legendFormat": "{{node}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Normalised Pod TX",
   "type": "timeseries",
   "description": "Displays data transmitted by each pod as percentage of node TX traffic on eth interface",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",node=~\"$node\",pod!~\"$ignore_pods_regexp\",pod!=\"\",pod=~\".*$pod_filter.*\"}[$__rate_interval])) by (node,pod)\n/ \non (node) group_left\nsum(label_replace(rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"eth.+\"}[$__rate_interval]),\"node\",\"$1\",\"nodename\",\"(.*)\")) by (node)\n",
     "legendFormat": "{{node}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Normalised Pod RX",
   "type": "timeseries",
   "description": "Displays data received by each pod as percentage of node RX traffic on eth interface",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=~\"$cluster\",node=~\"$node\",pod!~\"$ignore_pods_regexp\",pod!=\"\",pod=~\".*$pod_filter.*\"}[$__rate_interval])) by (node,pod)\n/ \non (node) group_left\nsum(label_replace(rate(node_network_receive_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"eth.+\"}[$__rate_interval]),\"node\",\"$1\",\"nodename\",\"(.*)\")) by (node)\n",
     "legendFormat": "{{node}}/{{pod}}"
    }
   ]
  }
 ]
}