{
 "title": "Networking cost estimation",
 "description": "Allows estimating AWS networking cost",
 "tags": [ "mojaloop" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_uname_info,cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info{cluster=~\"$cluster\"},nodename)"
    }
   },
   {
    "name": "s3_clients_pod_list",
    "query": "tempo-ingester|tempo-compactor|loki-ingester|loki-compactor|mimir-compactor|mimir-store-gateway|gitlab-registry"
   },
   { "name": "seconds_per_day", "query": "86400" },
   { "name": "bytes_per_GB", "query": "1073741824" },
   { "name": "inter_az_cost", "label": "Inter AZ cost ($)", "query": "0.01" },
   { "name": "vpn_cost", "label": "VPN cost ($)", "query": "0.163" },
   { "name": "internet_traffic_cost", "label": "Internet traffic cost ($)", "query": "0.145" },
   { "name": "s3_traffic_cost", "label": "S3 write cost ($)", "query": "0.145" }
  ]
 },
 "panels": [
  { "title": "RDS traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "External traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "External traffic (Internet and external services)",
   "type": "timeseries",
   "description": "Shows the estimated traffic sent to Internet and  external services. This doesn't include VPN traffic or inter k8s cluster traffic. \n\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"eth.+\"}[$__rate_interval]) \n- on(nodename)\nsum(rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"vxlan.calico|wt.+\"}[$__rate_interval])) without (device)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated daily volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"eth.+\"}[$__rate_interval]) \n- on(nodename)\nsum(rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"vxlan.calico|wt.+\"}[$__rate_interval])) without (device))\n*${seconds_per_day}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Estimated daily cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"eth.+\"}[$__rate_interval]) \n- on(nodename)\nsum(rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"vxlan.calico|wt.+\"}[$__rate_interval])) without (device))\n*${seconds_per_day}/${bytes_per_GB}*${internet_traffic_cost}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  { "title": "Inter cluster traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Intra cluster traffic",
   "type": "timeseries",
   "description": "Shows the pod traffic sent to other nodes of the same k8s cluster. This will incur interzone charges if other nodes are in different AZ.\n\nNOTE: It only includes egress as inter zone ingress is considered free",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"vxlan.calico\"}[$__rate_interval])\n",
     "legendFormat": "traffic: {{nodename}}"
    }
   ]
  },
  {
   "title": "Estimated daily volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"vxlan.calico\"}[$__rate_interval])*${seconds_per_day}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Estimated daily cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"vxlan.calico\"}[$__rate_interval])*${seconds_per_day}/${bytes_per_GB}*${inter_az_cost}\n",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Intercluster traffic (VPN traffic)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Intercluster traffic",
   "type": "timeseries",
   "description": "Traffic sent to other peers connected over netbird VPN",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"wt.+\"}[$__rate_interval])\n",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Estimated daily volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"wt.+\"}[$__rate_interval])*${seconds_per_day}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Estimated daily cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",nodename=~\"$node\",device=~\"wt.+\"}[$__rate_interval])*${seconds_per_day}/${bytes_per_GB}*${vpn_cost}\n",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  { "title": "S3 traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "S3 write estimate",
   "type": "timeseries",
   "description": "This estimate only includes logs, metrics, traces and gitlab registry ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",node=~\"$node\",pod=~\".*($s3_clients_pod_list).*\"}[$__rate_interval])) by (node)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated daily volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum(rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",node=~\"$node\",pod=~\".*($s3_clients_pod_list).*\"}[$__rate_interval])) by (node))\n*${seconds_per_day}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Estimated daily cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",node=~\"$node\",pod=~\".*($s3_clients_pod_list).*\"}[$__rate_interval])) by (node))\n*${seconds_per_day}/${bytes_per_GB}*${s3_traffic_cost}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "S3 write estimate",
   "type": "timeseries",
   "description": "This estimate only includes logs, metrics, traces and gitlab registry ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",node=~\"$node\",pod=~\".*($s3_clients_pod_list).*\"}[$__rate_interval])) by (node,pod)\n",
     "legendFormat": "{{node}}/{{pod}}"
    }
   ]
  }
 ]
}