{
 "title": "Mojaloop - Remote write resources overview",
 "description": "Shows the resource utilisation of Prometheus and Mimir write components",
 "tags": [
  "mojaloop",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_uname_info,cluster)"
    }
   },
   { "name": "rate_interval", "label": "rate interval", "query": "30s,1m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus traffic - sent ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{cluster=\"$cluster\",pod=~\".*prometheus-.*\",pod!~\".*operator.*\"}[${rate_interval}])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mimir distributor traffic - received ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\",pod=~\".*mimir-distributor.*\",}[${rate_interval}]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Prometheus RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",container=\"prometheus\"}) by (container,pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mimir ingester RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",container=~\"grafana-mimir-ingester\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Prometheus CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container=\"prometheus\"}[$rate_interval])) by (container,pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mimir CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container=~\"grafana-mimir-(distributor|ingester)\"}[$rate_interval])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Misl", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Estimated Prometheus storage (per day)",
   "type": "timeseries",
   "description": "Amount of storage needed for 1 day worth of prometheus data",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expression": "$A*$B*3600*24", "type": "math" }
   ]
  },
  {
   "title": "Estimated sample size (TSDB)",
   "type": "timeseries",
   "description": "Average sample size in TSDB after compaction",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes/sample" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{cluster=\"$cluster\",service=~\".*prometheus.*\"}[$rate_interval]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{cluster=\"$cluster\",service=~\".*prometheus.*\"}[$rate_interval]))",
     "legendFormat": "bytes per sample"
    }
   ]
  },
  {
   "title": "Samples per second",
   "type": "timeseries",
   "description": "No. of samples scraped per second",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{cluster=\"$cluster\",type=\"float\"}[$rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}