{
 "title": "Storage - Quick view",
 "tags": [
  "mojaloop",
  "storage"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"},namespace)"
    }
   },
   { "name": "pvc_name", "label": "PVC name" },
   { "name": "show_sum", "label": "Show sum", "query": "Yes : 1, No : No" },
   {
    "name": "ceph_pool_id",
    "query": {
     "query": "label_values(ceph_pool_metadata{cluster=\"$cluster\", name=~\".*(rgw.buckets.data|blockpool).*\"},pool_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Ceph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{cluster=~\"$cluster\"}",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Total capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{cluster=~\"$cluster\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Total utilisation (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{cluster=~\"$cluster\"}/ceph_cluster_total_bytes{cluster=~\"$cluster\"}",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Ceph pool utilisation (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_pool_stored{cluster=~\"$cluster\",pool_id=~\"$ceph_pool_id\"}/\n(ceph_pool_stored{cluster=~\"$cluster\",pool_id=~\"$ceph_pool_id\"}+ceph_pool_max_avail{cluster=~\"$cluster\",pool_id=~\"$ceph_pool_id\"}) \n* on (pool_id) group_left(name) ceph_pool_metadata{cluster=~\"$cluster\"}",
     "legendFormat": "pool: {{name}}"
    }
   ]
  },
  {
   "title": "Buckets approaching max quota limit",
   "type": "table",
   "description": "Indicates buckets which are very near to bucket quota limit. NOTE: bucket quota is being enforced using users quota",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(radosgw_usage_user_total_bytes{cluster=~\"$cluster\"}) by (user) / \nsum(radosgw_usage_user_quota_size_bytes{cluster=~\"$cluster\"} ) by (user) > 0.8 ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Persistent Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "PVC usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",persistentvolumeclaim=~\".*$pvc_name.*\",job=\"kubelet\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    },
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",persistentvolumeclaim=~\".*$pvc_name.*\",job=\"kubelet\"}) * ${show_sum}",
     "legendFormat": "sum of all series"
    }
   ]
  },
  {
   "title": "PVC Capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",persistentvolumeclaim=~\".*$pvc_name.*\",job=\"kubelet\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",persistentvolumeclaim=~\".*$pvc_name.*\",job=\"kubelet\"}) * ${show_sum}",
     "legendFormat": "sum of all series"
    }
   ]
  },
  {
   "title": "PVC utilisation (%) ",
   "type": "timeseries",
   "description": "usage/capacity percentage",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",persistentvolumeclaim=~\".*$pvc_name.*\",job=\"kubelet\"}\n/\nkubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",persistentvolumeclaim=~\".*$pvc_name.*\",job=\"kubelet\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}