apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restart-ceph-rgw-server
  annotations:
    policies.kyverno.io/title: Restart Ceph RGW server on secret update
    policies.kyverno.io/category: Default Policies
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      This policy requires the restart of Radosgw server when the secret is updated
    argocd.argoproj.io/sync-wave: "0"
spec:
  rules:
    - name: restart-rgw-deployment-on-tls-update
      match:
        any:
        - resources:
            kinds:
              - Secret
            names:
              - objectstore-internal-tls
            namespaces:
              - ${ARGOCD_ENV_storage_namespace}
      preconditions:
        all:
          - key: "{{request.operation}}"
            operator: Equals
            value: UPDATE
      mutate:
        targets:
          - apiVersion: apps/v1
            kind: Deployment
            namespace: ${ARGOCD_ENV_storage_namespace}
            selector:
              matchLabels:
                app: rook-ceph-rgw
        patchStrategicMerge:
          spec:
            template:
              metadata:
                annotations:
                  cert-rotation-timestamp: "{{ time_now_utc() }}"
