apiVersion: utils.aws.mojaloop.io/v1alpha1
kind: AWSRoute53Record
metadata:
  name: sck8s-hostname
  namespace: ${ARGOCD_ENV_external_dns_namespace}
  annotations:
     argocd.argoproj.io/sync-wave: '-5'
spec:
  parameters:
    name: ${ARGOCD_ENV_capi_cluster_kubeapi_fqdn}
    region: eu-west-1
    ttl: 300
    type: A
    records:
      - ${ARGOCD_ENV_capi_cluster_kubeapi_host}
    zoneId: ${ARGOCD_ENV_dns_zone_id}
  providerConfigsRef:
    awsProviderConfigName: aws-cp-upbound-provider-config